### ISSUE TITLE
New annotations not getting a yellow highlight

### ISSUE THREAD

**Issue by alykat** [nprapps/anno-docs#70]
The footer for a live transcription says:

![image](https://user-images.githubusercontent.com/491318/73808165-f474ff80-479c-11ea-848a-22c637ef5bec.png)

But as I scroll down (in Chrome/Mac), i'm not actually seeing the yellow highlighting on new posts. I do see some occasionally animate in.

**Comment by thomaswilburn** [comment]
@DanielJWood Was this fixed? I see a commit that looks like a likely candidate, but the issue remains open.

**Comment by DanielJWood** [comment]
Yes I believe it was fixed [here](https://github.com/nprapps/anno-docs/commit/11784505dac7384b4d419df5c94b150c75127871). Not sure why but the css that was controlling this had been commented out.

**Comment by alykat** [comment]
Looks like Juan had intended to comment it out for non-live events (but maybe that ended up affecting live events, too).

https://github.com/nprapps/anno-docs/blame/cbea0b795b844a2d7f652b393c14c9da1e53ad6d/less/app.less#L359
